"""
Live Ingestion Gateway Layer for Sentinel-Agent.
Exposes an asynchronous FastAPI REST endpoint to listen for production webhooks.
"""

import logging
from fastapi import FastAPI, status
from pydantic import BaseModel
from typing import Dict, Any

# Core Configurations & Workflow imports pointing to your exact project structure
from app.config import settings
from app.Langgraph_agent_Orchestrator.graph.workflow import healing_pipeline_engine

# Setup clean server log tracking
logging.basicConfig(
    level=logging.INFO, 
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("SentinelGateway")

app = FastAPI(
    title="Sentinel-Agent Ingestion Gateway",
    description="24/7 Autonomous Self-Healing Operations Engine Node"
)

# Define the data verification schema matching your Postman payload keys
class WebhookPayload(BaseModel):
    incident_id: str
    source_system: str
    raw_logs: str


def execute_agent_pipeline(initial_state: Dict[str, Any]):
    """
    Background worker thread tasked with running the heavy multi-agent 
    reasoning loop without clogging up the public HTTP request lines.
    """
    logger.info(f"⚡ [WORKER] Initializing LangGraph self-healing loop for incident {initial_state['incident_id']}...")
    try:
        # Call the orchestrator's invoke method directly. Some StateGraph wrappers
        # expose invoke on the engine object itself rather than a .graph attribute.
        final_state = healing_pipeline_engine.invoke(initial_state)
        logger.info(f"✅ [WORKER] Self-healing workflow successfully completed for incident {initial_state['incident_id']}.")
        
        # This will cleanly print the full dynamic Markdown report to your server terminal window!
        print("\n" + "="*60)
        print(final_state.get("final_rca_report", "⚠️ No RCA report generated."))
        print("="*60 + "\n")
        
    except Exception as e:
        logger.error(f"❌ [WORKER] Pipeline execution failed for incident {initial_state['incident_id']}: {e}", exc_info=True)


@app.get("/health", status_code=status.HTTP_202_ACCEPTED)
def health_check():
    """Uptime monitoring endpoint to confirm server vitality."""
    return {"status": "online", "service": "sentinel-agent-gateway"}


@app.post("/webhook/incident", status_code=status.HTTP_200_OK)
async def receive_incident_alert(payload: WebhookPayload):
    """
    Core ingestion webhook listener. Accepts incident traffic payloads
    and instantly hands them off to background processing routines.
    """
    logger.info(f"📥 Received incoming webhook crash alert from [{payload.source_system}] for ID: {payload.incident_id}")
    
    # Structure data contract directly conforming to your DevOpsAgentState schema layout
    graph_initial_state = {
        "incident_id": payload.incident_id,
        "source_system": payload.source_system,
        "raw_logs": payload.raw_logs,
        "target_file": "",
        "commit_author": "",
        "priority_level": "",
        "proposed_patch": "",
        "critic_feedback": [], # Explicitly initialized as an array tracker list
        "critic_approved": False,
        "retry_counter": 0,
        "is_fixed": False,
        "final_rca_report": "",
        "incident_context": {},
        "repository_context": {},
        "slack_context": {},
        "sandbox_result": {},
        "slack_notification": {},
        "source_modes": {},
    }

    try:
        final_state = healing_pipeline_engine.invoke(graph_initial_state)
        return {
            "message": "Incident payload processed. RCA generated by Sentinel-Agent.",
            "incident_id": payload.incident_id,
            "target_file": final_state.get("target_file", ""),
            "priority_level": final_state.get("priority_level", ""),
            "is_fixed": final_state.get("is_fixed", False),
            "source_modes": final_state.get("source_modes", {}),
            "incident_context": final_state.get("incident_context", {}),
            "sandbox_result": final_state.get("sandbox_result", {}),
            "slack_notification": final_state.get("slack_notification", {}),
            "proposed_patch": final_state.get("proposed_patch", ""),
            "final_rca_report": final_state.get("final_rca_report", ""),
        }
    except Exception as e:
        logger.error(f"❌ Pipeline execution failed for incident {payload.incident_id}: {e}", exc_info=True)
        return {
            "message": "Incident payload ingested, but Sentinel-Agent failed while generating the RCA.",
            "incident_id": payload.incident_id,
            "error": str(e),
        }
